--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST_LIKES
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."POST_LIKES" 
   (	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(50), 
	 PRIMARY KEY ("POST_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_POST_LIKES_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "PROJECT_2"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007225
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007225" ON "PROJECT_2"."POST_LIKES" ("POST_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table POST_LIKES
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."POST_LIKES" ADD PRIMARY KEY ("POST_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table POST_LIKES
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."POST_LIKES" ADD CONSTRAINT "FK_POST_LIKES_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "PROJECT_2"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE
  ALTER TABLE "PROJECT_2"."POST_LIKES" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
