--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."REPORTS" 
   (	"REPORT_ID" NUMBER, 
	"TARGET_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"TARGET_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(500), 
	"REPORTER_ID" VARCHAR2(50), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20) DEFAULT '대기' NOT NULL ENABLE, 
	 PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("REPORTER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007250
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007250" ON "PROJECT_2"."REPORTS" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."REPORTS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "PROJECT_2"."REPORTS" ADD PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECT_2"."REPORTS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE)
  ALTER TABLE "PROJECT_2"."REPORTS" MODIFY ("TARGET_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."REPORTS" ADD FOREIGN KEY ("REPORTER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
