--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCRAPS
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."SCRAPS" 
   (	"SCRAP_ID" NUMBER, 
	"USER_ID" VARCHAR2(100), 
	"POST_ID" NUMBER, 
	"SCRAP_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SCRAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_SCRAPS_USER_POST" UNIQUE ("USER_ID", "POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SCRAPS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_SCRAPS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "PROJECT_2"."POSTS" ("POST_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007232
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007232" ON "PROJECT_2"."SCRAPS" ("SCRAP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UQ_SCRAPS_USER_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."UQ_SCRAPS_USER_POST" ON "PROJECT_2"."SCRAPS" ("USER_ID", "POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."SCRAPS" ADD CONSTRAINT "UQ_SCRAPS_USER_POST" UNIQUE ("USER_ID", "POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECT_2"."SCRAPS" ADD PRIMARY KEY ("SCRAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."SCRAPS" ADD CONSTRAINT "FK_SCRAPS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "PROJECT_2"."POSTS" ("POST_ID") ENABLE
  ALTER TABLE "PROJECT_2"."SCRAPS" ADD CONSTRAINT "FK_SCRAPS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
