--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDY_STATS
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."STUDY_STATS" 
   (	"STAT_ID" NUMBER, 
	"USER_ID" VARCHAR2(50), 
	"PERIOD_TYPE" VARCHAR2(10), 
	"PERIOD_START" DATE, 
	"PERIOD_END" DATE, 
	"TOTAL_MINUTES" NUMBER, 
	 PRIMARY KEY ("STAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007207
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007207" ON "PROJECT_2"."STUDY_STATS" ("STAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table STUDY_STATS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_STATS" ADD PRIMARY KEY ("STAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table STUDY_STATS
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_STATS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
