--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDY_MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."STUDY_MEMBER" 
   (	"GROUP_ID" NUMBER, 
	"USER_ID" VARCHAR2(50), 
	"JOIN_DATE" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(20), 
	 PRIMARY KEY ("GROUP_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_STUDY_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "PROJECT_2"."STUDY_GROUP" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007216
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007216" ON "PROJECT_2"."STUDY_MEMBER" ("GROUP_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table STUDY_MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_MEMBER" ADD PRIMARY KEY ("GROUP_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table STUDY_MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_MEMBER" ADD CONSTRAINT "FK_STUDY_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "PROJECT_2"."STUDY_GROUP" ("GROUP_ID") ON DELETE CASCADE ENABLE
