--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDY_GROUP
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."STUDY_GROUP" 
   (	"GROUP_ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"LEADER_ID" VARCHAR2(50), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"DURATION" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000), 
	"MAX_MEMBER" NUMBER(3,0), 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("LEADER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007214
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007214" ON "PROJECT_2"."STUDY_GROUP" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table STUDY_GROUP
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_GROUP" ADD PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table STUDY_GROUP
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."STUDY_GROUP" ADD FOREIGN KEY ("LEADER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
