--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TODO_LIST
--------------------------------------------------------

  CREATE TABLE "PROJECT_2"."TODO_LIST" 
   (	"TODO_ID" NUMBER, 
	"USER_ID" VARCHAR2(50), 
	"SUBJECT" VARCHAR2(100), 
	"CONTENT" VARCHAR2(500), 
	"DEADLINE" DATE, 
	"GOAL" VARCHAR2(200), 
	"STATUS" VARCHAR2(20), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"FEEDBACK" VARCHAR2(500), 
	"TOTAL" NUMBER(10,0), 
	 CHECK (STATUS IN ('완료', '미완료')) ENABLE, 
	 PRIMARY KEY ("TODO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007201
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT_2"."SYS_C007201" ON "PROJECT_2"."TODO_LIST" ("TODO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger TODO_LIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJECT_2"."TODO_LIST_TRG" 
BEFORE INSERT ON TODO_LIST
FOR EACH ROW
 WHEN (NEW.TODO_ID IS NULL) BEGIN
  SELECT PROJECT_2.TODO_LIST_SEQ.NEXTVAL INTO :NEW.TODO_ID FROM DUAL;
END;

ALTER TRIGGER "PROJECT_2"."TODO_LIST_TRG" ENABLE
--------------------------------------------------------
--  Constraints for Table TODO_LIST
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."TODO_LIST" ADD PRIMARY KEY ("TODO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECT_2"."TODO_LIST" ADD CHECK (STATUS IN ('완료', '미완료')) ENABLE
--------------------------------------------------------
--  Ref Constraints for Table TODO_LIST
--------------------------------------------------------

  ALTER TABLE "PROJECT_2"."TODO_LIST" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "PROJECT_2"."USERS" ("USER_ID") ENABLE
